export const students = [
  {
    id: 1,
    name: "John",
    email: "john@example.com",
    courseName: "HTML & CSS",
    age: 19,
    city: "Mumbai",
    status: "Active",
  },
  {
    id: 2,
    name: "Emma Watson",
    email: "emma@example.com",
    courseName: "JavaScript",
    age: 21,
    city: "Delhi",
    status: "Active",
  },
  {
    id: 3,
    name: "Michael Scott",
    email: "michael@example.com",
    courseName: "Bootstrap",
    age: 24,
    city: "Pune",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Sophia Brown",
    email: "sophia@example.com",
    courseName: "Java",
    age: 22,
    city: "Bengaluru",
    status: "Active",
  },
  {
    id: 5,
    name: "David Miller",
    email: "david@example.com",
    courseName: "JavaScript",
    age: 23,
    city: "Hyderabad",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Olivia Wilson",
    email: "olivia@example.com",
    courseName: "HTML & CSS",
    age: 20,
    city: "Ahmedabad",
    status: "Active",
  },
];